name: Continuous Deployment

on:
  push:
    branches: [ "celana-dalam" ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment'
        required: false
        type: boolean
        default: false

env:
  DEPLOY_PATH: ~/lokakarya/be
  COMPOSE_FILE: docker-compose.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Create deployment directory if it doesn't exist
          mkdir -p ${{ env.DEPLOY_PATH }}
          
          # Remove existing deployment artifacts
          rm -rf ${{ env.DEPLOY_PATH }}/*
      
    - name: Copy Deployment Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "*"
        target: ${{ env.DEPLOY_PATH }}

    - name: Cek ada apa aja
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          ls -la ${{ env.DEPLOY_PATH }}
    
    - name: mvmv
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          mv ${{ env.DEPLOY_PATH }}/deployment-artifacts/* ${{ env.DEPLOY_PATH }}

    - name: Execute Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          export DB_NAME=${{ secrets.DB_NAME }}
          export DB_USERNAME=${{ secrets.DB_USERNAME }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
          export DB_DRIVER_NAME=${{ secrets.DB_DRIVER_NAME }}
          export JWT_SECRET=${{ secrets.JWT_SECRET }}
          export JWT_EXPIRATION_MS=${{ secrets.JWT_EXPIRATION_MS }}
          export APP_PORT=${{ secrets.APP_PORT }}
          cd ${{ env.DEPLOY_PATH }}
          
          # Pull latest images
          docker-compose pull
          
          # Stop existing containers
          docker-compose down
          
          # Start new containers
          docker-compose up
          
          # Clean up unused docker resources
          docker system prune -af --volumes